In [1]:
import requests
import os
from dotenv import load_dotenv
import pandas as pd
from datetime import datetime

In [2]:
load_dotenv()
WAQI_TOKEN = os.getenv("WAQI_TOKEN")

In [3]:
LAT, LON = 30.1978 , 71.4719

## AQICN

In [4]:
# url = f"https://api.waqi.info/feed/multan/?token={WAQI_TOKEN}"
# response = requests.get(url)
# data = response.json()

# print(data)

In [5]:
# station_ids = {
#     "Women University": "A544288",
#     "District Officer Industries": "A544444",
#     "BZU Multan": "A576622",
#     "Walled Cities Authority": "A544066"
# }

# for name, station_id in station_ids.items():
#     url = f"https://api.waqi.info/feed/{station_id}/?token={WAQI_TOKEN}"
#     resp = requests.get(url).json()
#     if resp["status"] == "ok":
#         aqi = resp["data"].get("aqi", "N/A")
#         time = resp["data"]["time"]["s"]
#         print(f"{name}: AQI={aqi}, last reported={time}")
#     else:
#         print(f"{name}: ERROR - {resp}")

In [6]:
# url = f"https://api.waqi.info/feed/A544288/?token={WAQI_TOKEN}"
# response = requests.get(url)
# data = response.json()
# print(data)

In [7]:
# url = f"https://api.waqi.info/feed/A544288/?token={WAQI_TOKEN}"
# resp = requests.get(url).json()

# data = resp["data"]
# iaqi = data["iaqi"]  # nested dict of individual pollutants

# flat = {"aqi": data["aqi"], "timestamp": data["time"]["s"]}
# for pollutant, val in iaqi.items():
#     flat[pollutant] = val["v"]

# print(flat)

## Open Meteo

In [8]:
url = "https://api.open-meteo.com/v1/forecast"
params = {
    "latitude": LAT,
    "longitude": LON,
    "current": "temperature_2m,relative_humidity_2m,wind_speed_10m,surface_pressure,cloud_cover,precipitation",
    "timezone": "Asia/Karachi"
}

resp = requests.get(url, params=params).json()
print(resp)

{'latitude': 30.193321, 'longitude': 71.47369, 'generationtime_ms': 0.12004375457763672, 'utc_offset_seconds': 18000, 'timezone': 'Asia/Karachi', 'timezone_abbreviation': 'GMT+5', 'elevation': 143.0, 'current_units': {'time': 'iso8601', 'interval': 'seconds', 'temperature_2m': '°C', 'relative_humidity_2m': '%', 'wind_speed_10m': 'km/h', 'surface_pressure': 'hPa', 'cloud_cover': '%', 'precipitation': 'mm'}, 'current': {'time': '2026-08-04T15:30', 'interval': 900, 'temperature_2m': 35.7, 'relative_humidity_2m': 57, 'wind_speed_10m': 8.9, 'surface_pressure': 982.8, 'cloud_cover': 9, 'precipitation': 0.0}}

In [20]:
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
    "latitude": LAT,
    "longitude": LON,
    "start_date": "2025-08-01",
    "end_date": "2026-07-31",
    "hourly": "temperature_2m,relative_humidity_2m,wind_speed_10m,surface_pressure,cloud_cover,precipitation",
    "timezone": "Asia/Karachi"
}

resp = requests.get(url, params=params).json()
df_weather = pd.DataFrame(resp["hourly"])

df_weather.head()

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,surface_pressure,cloud_cover,precipitation
0,2025-08-01T00:00,31.4,74,5.8,982.1,13,0.0
1,2025-08-01T01:00,30.9,77,6.7,981.8,84,0.0
2,2025-08-01T02:00,30.6,77,6.1,981.4,100,0.0
3,2025-08-01T03:00,30.4,76,5.5,981.1,100,0.0
4,2025-08-01T04:00,30.1,74,6.1,981.3,100,0.0

In [10]:
url = "https://air-quality-api.open-meteo.com/v1/air-quality"
params = {
    "latitude": LAT,
    "longitude": LON,
    "current": "us_aqi,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,dust,ammonia",
    "timezone": "Asia/Karachi"
}

resp = requests.get(url, params=params).json()
print(resp["current"])

{'time': '2026-08-04T15:00', 'interval': 3600, 'us_aqi': 114, 'pm2_5': 32.7, 'pm10': 48.2, 'carbon_monoxide': 321.0, 'nitrogen_dioxide': 1.7, 'sulphur_dioxide': 5.6, 'ozone': 134.0, 'dust': 27.0, 'ammonia': None}

In [21]:
url = "https://air-quality-api.open-meteo.com/v1/air-quality"
params = {
    "latitude": LAT,
    "longitude": LON,
    "start_date": "2025-08-01",
    "end_date": "2026-07-31",
    "hourly": "us_aqi,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,dust",
    "timezone": "Asia/Karachi"
}

resp = requests.get(url, params=params).json()
df_aqi = pd.DataFrame(resp["hourly"])

df_aqi.head()

,time,us_aqi,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,dust
0,2025-08-01T00:00,152,77.3,122.9,378.0,24.8,5.4,49.0,86.0
1,2025-08-01T01:00,153,75.0,120.1,342.0,22.9,5.1,46.0,90.0
2,2025-08-01T02:00,153,73.8,122.0,315.0,21.9,4.9,42.0,93.0
3,2025-08-01T03:00,154,74.0,129.5,293.0,22.8,4.8,37.0,92.0
4,2025-08-01T04:00,154,70.1,123.4,278.0,24.5,4.8,32.0,90.0

In [22]:
print(df_weather.shape)
print(df_weather.isnull().sum())

print(df_aqi.shape)
print(df_aqi.isnull().sum())

(8760, 7)
time                    0
temperature_2m          0
relative_humidity_2m    0
wind_speed_10m          0
surface_pressure        0
cloud_cover             0
precipitation           0
dtype: int64
(8760, 9)
time                0
us_aqi              0
pm2_5               0
pm10                0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dust                0
dtype: int64

## Merging

In [23]:
df_merged = pd.merge(df_weather, df_aqi, on="time", how="inner")
print(df_merged.shape)
df_merged.head()

(8760, 15)

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,surface_pressure,cloud_cover,precipitation,us_aqi,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,dust
0,2025-08-01T00:00,31.4,74,5.8,982.1,13,0.0,152,77.3,122.9,378.0,24.8,5.4,49.0,86.0
1,2025-08-01T01:00,30.9,77,6.7,981.8,84,0.0,153,75.0,120.1,342.0,22.9,5.1,46.0,90.0
2,2025-08-01T02:00,30.6,77,6.1,981.4,100,0.0,153,73.8,122.0,315.0,21.9,4.9,42.0,93.0
3,2025-08-01T03:00,30.4,76,5.5,981.1,100,0.0,154,74.0,129.5,293.0,22.8,4.8,37.0,92.0
4,2025-08-01T04:00,30.1,74,6.1,981.3,100,0.0,154,70.1,123.4,278.0,24.5,4.8,32.0,90.0

In [24]:
df_merged.to_csv(r"..\Data\sample_data.csv",index=False)